### ISSUE TITLE
no /proc/cpuinfo on solaris

### ISSUE THREAD

**Issue by bjoernrost** [carlos-sierra/edb360#1]
Just running edb360 on a solaris box and just noticed this error right at the beginning

```
cat: cannot open /proc/cpuinfo: No such file or directory
```

Obviously there is no /proc/cpuinfo on Solaris. One could get that information from prtdiag instead. But then one would have to check for the OS first and possibly create yet another script. Or simply live with an empty output file for `cpuinfo_model_name.txt`. I guess this is not a big issue as long as nothing else depends on the output of this check being not empty

cheers
bjoern

**Comment by carlos-sierra** [comment]
no dependencies. ignore error.

Carlos Sierra
Life is Good!
