### ISSUE TITLE
Not working, not clear what the requirements are

### ISSUE THREAD

**Issue by SebTardif** [carlos-sierra/edb360#5]
Using the same environment SQL Health Check is working perfectly fine.

However, edb360 Jan 15, 2018 version is not doing much, and showing lot of errors.

Now zip file seems to be generated.

See attachment for the shell output when executing sqlplus without any user prompt.

[executions1787237285448039367 2.txt](https://github.com/carlos-sierra/edb360/files/1737588/executions1787237285448039367.2.txt)

**Comment by carlos-sierra** [comment]
/bin/sh: 00004_edb360_549470_log3.txt: Permission denied

**Comment by carlos-sierra** [comment]
it seems you may have some permission issues writing to local directory.

**Comment by SebTardif** [comment]
It seems the issue compared to SQLHC and SQLT that work fine, is that edb360 cannot handle that the current folder is not the script folder. So I setup the 'current folder' to be edb360 script instead of a temp folder that I used with SQLHC and SQLT, but then the script folder is read-only. Would be great if edb360 could load it sub-scripts relative to the main entry point script called or we could tell edb360 where to write stuff ( the temp folder).

**Comment by carlos-sierra** [comment]
Not sure what exactly you are trying to do. eDB360 writes into its current folder. You may want to put eDB360 on /tmp if you want to write there. Or look into configuration parameters, there is one that gets you near that, but there are some pieces of eDB360 that will try to write to its current folder anyways, like AWR reports. I just follow the instructions and always execute from within the script folder.

**Comment by SebTardif** [comment]
I put everything in the temp folder and it's now working. I was hoping to see more top x, y, z about SQLs, like top 20 elapsed time.

**Comment by carlos-sierra** [comment]
Top SQL shows in column 6. It only shows them as per DB Time. 
On next upload, I will add a section that will show top SQL (default 20) as per:
PRO Metrics
PRO ~~~~~~~~~~~~~~~~~~~
PRO elapsed_time_delta
PRO cpu_time_delta
PRO iowait_delta
PRO apwait_delta
PRO ccwait_delta
PRO parse_calls_delta
PRO executions_delta
PRO fetches_delta
PRO loads_delta
PRO invalidations_delta
PRO version_count
PRO sharable_mem
PRO rows_processed_delta
PRO buffer_gets_delta
PRO disk_reads_delta

**Comment by SebTardif** [comment]
Thanks to plan adding more of this kind of info. Right now I have pretty much nothing in column 6, maybe because I don't have any of extra package (tuning,...). Wonder if your queries will check v$sql, because I do have information there even if I have none of the extra packages and running on standard edition.

**Comment by carlos-sierra** [comment]
Most of my tools are based on AWR. When diagnosing performance, not having Diagnostics Pack leave you with few options, such as Statspack, Trace/TKPROF and snapper.sql from Tanel
